# Generated by Django 5.2.6 on 2025-10-02 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertask',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('executor', 'Executor')], default='owner'),
        ),
        migrations.AddField(
            model_name='usertask',
            name='work_time',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('feature', 'Feature'), ('bugfix', 'Bugfix'), ('hotfix', 'Hotfix')], default=2),
        ),
    ]
