# Generated by Django 5.2.6 on 2025-10-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_branchestask_task_alter_usertask_task'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='usertask',
            constraint=models.UniqueConstraint(fields=('task', 'user'), name='unique_user_task_participant'),
        ),
    ]
