# Generated by Django 5.2.6 on 2025-10-31 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_usertask_unique_user_task_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchestask',
            name='user_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.usertask'),
        ),
    ]
